export const questions = [
  {
    id: 1,
    question: `What color is Mace Windu's lightsaber?`,
    answer1: 'PURPLE',
    answer2: 'BLACK',
    answer3: 'BLUE',
    answer4: 'GREEN',
    correct: 'PURPLE',
  },
  {
    id: 2,
    question: 'Who is the only non Jedi in the original Star Wars trilogy to use a lightsaber?',
    answer1: 'HAN SOLO',
    answer2: 'PRINCESS LEIA',
    answer3: 'R2-D2',
    answer4: 'CHEWBACCA',
    correct: 'HAN SOLO',
  },
  {
    id: 3,
    question: 'Approximately how many languages can C-3PO speak?',
    answer1: '6 MILLION',
    answer2: '6 THOUSAND',
    answer3: '6 TRILLION',
    answer4: '6 BILLION',
    correct: '6 MILLION',
  },
  {
    id: 4,
    question: 'What does Han say when Leia first tells him that she loveshim?',
    answer1: `"I KNOW"`,
    answer2: `"IT'S ABOUT TIME"`,
    answer3: `"I FIGURED"`,
    answer4: `"I LOVE YOU, TOO"`,
    correct: `"I KNOW`,
  },
  {
    id: 5,
    question: 'Who is the commander of the Death Star in A New Hope?',
    answer1: 'WILHUFF TARKIN',
    answer2: 'LORTH NEEDA',
    answer3: 'DARTH VADER',
    answer4: 'MOFF GIDEON',
    correct: 'WILHUFF TARKIN',
  },
];